function parameterTuning_linear_nolabel(hMainFigure,parameter,parameterMin,parameterMax,slider_pos,value_pos,push_pos,txt_pos,step_pos)

% Map slider position to specified range
initial = parameter.value;
rangeVector = linspace(parameterMin,parameterMax,2001);
[~,idx] = min(abs(rangeVector-parameter.value));
initialSliderPosition = idx/2000;
    
    % Slider to tune parameter
    uicontrol('Parent',hMainFigure, ...
        'Style','slider', ...
        'Position',slider_pos, ...
        'Value',initialSliderPosition, ...
        'Callback',@slidercb);
    
    % Display current parameter value
    paramValueDisplay = uicontrol('Parent',hMainFigure, ...
        'Style','text', ...
        'Position', value_pos, ...
        'BackgroundColor','white', ...
        'String',parameter.value);
    
    uicontrol('Parent',hMainFigure, ...
        'Style','pushbutton', ...
        'Position',push_pos, ...
        'String','Reset', ...
        'Callback',@reset);
    
    uicontrol('Parent',hMainFigure, ...
        'Style','edit', ...
        'Position',step_pos, ...
        'Value',parameter.step, ...
        'Callback',@edit_step);
    
    uicontrol('Parent',hMainFigure, ...
        'Style','text', ...
        'Position',txt_pos, ...
        'String','Step size:');
    
    % Update parameter value if slider value changed
    function slidercb(slider,~)
        val = get(slider,'Value');
        rangeVectorIndex = round(val*2000)+1;
        parameter.value = rangeVector(rangeVectorIndex);
        set(paramValueDisplay,'String',num2str(parameter.value));
    end

    function reset(slider,~)
        parameter.value = initial;
        set(paramValueDisplay,'String',num2str(parameter.value));
    end

    function edit_step(edit,~)
        val = get(edit,'String');
        parameter.step = str2double(val);
    end
end