function parameterTuning_sub(hMainFigure,parameter,parameterMin,parameterMax,label_pos,slider_pos,value_pos,push_pos)

% Map slider position to specified range
initial = parameter.value;
rangeVector = [linspace(parameterMin,initial,1000) linspace(initial,parameterMax,1001)];
[~,idx] = min(abs(rangeVector - initial));
initialSliderPosition = idx/2000;
    
    % Slider to tune parameter
    uicontrol('Parent',hMainFigure, ...
        'Style','slider', ...
        'Position',slider_pos, ...
        'Value',initialSliderPosition, ...
        'Callback',@slidercb);
    
    % Label for slider
    uicontrol('Parent',hMainFigure, ...
        'Style','text', ...
        'Position',label_pos, ...
        'BackgroundColor','white', ...
        'String',parameter.name);
    
    % Display current parameter value
    paramValueDisplay = uicontrol('Parent',hMainFigure, ...
        'Style','text', ...
        'Position', value_pos, ...
        'BackgroundColor','white', ...
        'String',parameter.value);
    
    uicontrol('Parent',hMainFigure, ...
        'Style','pushbutton', ...
        'Position',push_pos, ...
        'String','Reset', ...
        'Callback',@reset);
    
    % Update parameter value if slider value changed
    function slidercb(slider,~)
        val = get(slider,'Value');
        rangeVectorIndex = round(val*2000)+1;
        parameter.value = rangeVector(rangeVectorIndex);
        set(paramValueDisplay,'String',num2str(parameter.value));
    end

    function reset(slider,~)
        parameter.value = initial;
        set(paramValueDisplay,'String',num2str(parameter.value));
    end
end