function midi(parent,parameter)
bg = uibuttongroup('Parent',parent, ...
                  'Visible','on',...
                  'Position',[0 0 1 1],...
                  'BackgroundColor','yellow', ...
                  'SelectionChangedFcn',@bselection);
              

% Create three radio buttons in the button group.
      
uicontrol(bg,'Style','radiobutton',...
                  'String','Disable',...
                  'Position',[5 5 100 30],...
                  'BackgroundColor','red', ...
                  'HandleVisibility','off');
              
% row 1
uicontrol(bg,'Style','radiobutton',...
                  'String','C2 (36)',...
                  'Position',[5 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','C#2(37)',...
                  'Position',[82 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D2 (38)',...
                  'Position',[159 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D#2(39)',...
                  'Position',[236 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','E2 (40)',...
                  'Position',[313 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F2 (41)',...
                  'Position',[390 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F#2(42)',...
                  'Position',[467 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G2 (43)',...
                  'Position',[544 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G#2(44)',...
                  'Position',[621 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A2 (45)',...
                  'Position',[698 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A#2(46)',...
                  'Position',[775 255 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','B2 (47)',...
                  'Position',[852 255 70 30],...
                  'HandleVisibility','off');
              
% row 2
uicontrol(bg,'Style','radiobutton',...
                  'String','C3 (48)',...
                  'Position',[5 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','C#3(49)',...
                  'Position',[82 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D3 (50)',...
                  'Position',[159 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D#3(51)',...
                  'Position',[236 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','E3 (52)',...
                  'Position',[313 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F3 (53)',...
                  'Position',[390 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F#3(54)',...
                  'Position',[467 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G3 (55)',...
                  'Position',[544 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G#3(56)',...
                  'Position',[621 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A3 (57)',...
                  'Position',[698 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A#3(58)',...
                  'Position',[775 220 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','B3 (59)',...
                  'Position',[852 220 70 30],...
                  'HandleVisibility','off');
              
% row 3
uicontrol(bg,'Style','radiobutton',...
                  'String','C4 (60)',...
                  'Position',[5 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','C#4(61)',...
                  'Position',[82 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D4 (62)',...
                  'Position',[159 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D#4(63)',...
                  'Position',[236 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','E4 (64)',...
                  'Position',[313 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F4 (65)',...
                  'Position',[390 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F#4(66)',...
                  'Position',[467 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G4 (67)',...
                  'Position',[544 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G#4(68)',...
                  'Position',[621 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A4 (69)',...
                  'Position',[698 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A#4(70)',...
                  'Position',[775 185 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','B4 (71)',...
                  'Position',[852 185 70 30],...
                  'HandleVisibility','off');
              
% row 4
uicontrol(bg,'Style','radiobutton',...
                  'String','C5 (72)',...
                  'Position',[5 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','C#5(73)',...
                  'Position',[82 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D5 (74)',...
                  'Position',[159 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D#5(75)',...
                  'Position',[236 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','E5 (76)',...
                  'Position',[313 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F5 (77)',...
                  'Position',[390 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F#5(78)',...
                  'Position',[467 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G5 (79)',...
                  'Position',[544 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G#5(80)',...
                  'Position',[621 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A5 (81)',...
                  'Position',[698 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A#5(82)',...
                  'Position',[775 150 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','B5 (83)',...
                  'Position',[852 150 70 30],...
                  'HandleVisibility','off');
              
% row 5
uicontrol(bg,'Style','radiobutton',...
                  'String','C6 (84)',...
                  'Position',[5 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','C#6(85)',...
                  'Position',[82 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D6 (86)',...
                  'Position',[159 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','D#6(87)',...
                  'Position',[236 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','E6 (88)',...
                  'Position',[313 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F6 (89)',...
                  'Position',[390 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','F#6(90)',...
                  'Position',[467 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G6 (91)',...
                  'Position',[544 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','G#6(92)',...
                  'Position',[621 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A6 (93)',...
                  'Position',[698 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','A#6(94)',...
                  'Position',[775 115 70 30],...
                  'HandleVisibility','off');
              
uicontrol(bg,'Style','radiobutton',...
                  'String','B6 (95)',...
                  'Position',[852 115 70 30],...
                  'HandleVisibility','off');
              
% row 6
              
uicontrol('Parent',parent, ...
        'Style','text', ...
        'Position', [5 75 100 30], ...
        'String','Autotune Frequency(Hz)');
    
% Display current frequency value
 paramValueDisplay = uicontrol('Parent',parent, ...
        'Style','text', ...
        'Position', [5 40 100 30], ...
        'BackgroundColor','white', ...
        'String',parameter.value);

              
% column 9
uicontrol('Parent',parent, ...
        'Style','text', ...
        'Position', [115 75 100 30], ...
        'String','Original Frequency(Hz)');
    
uicontrol('Parent',parent, ...
        'Style','text', ...
        'Position', [225 75 100 30], ...
        'String','Original Midi Number');
              
uicontrol('Parent',parent, ...
        'Style','text', ...
        'Position', [335 75 100 30], ...
        'String','Maximum Deviation(Hz)');
    
uicontrol('Parent',parent, ...
        'Style','text', ...
        'Position', [335 40 100 30], ...
        'String','Set Frequency(Hz)');
    
uicontrol('Parent',parent, ...
        'Style','text', ...
        'Position', [335 5 100 30], ...
        'BackgroundColor','green', ...
        'String','Set Speed Ratio');
              
% uicontrol('Parent',parent, ...
%         'Style','pushbutton', ...
%         'Position', [555 5 100 30], ...
%         'BackgroundColor','magenta', ...
%         'String','Anti-phase');
    
uicontrol('Parent',parent, ...
        'Style','text', ...
        'Position', [115 5 100 30], ...
        'BackgroundColor','green', ...
        'String','Delay step size');
    
% Make the uibuttongroup visible after creating child objects. 
% bg.Visible = 'on';

    function bselection(~,event)
       parameter.step = 1;
       midi_num = str2double(event.NewValue.String(5:6));
       parameter.value = 440*2^((midi_num-69)/12);
       set(paramValueDisplay,'String',num2str(parameter.value));
    end
end